before_install:
  - travis_retry make node_modules
  - source ./tests/travis_ci/venv.sh
install: ./node_modules/.bin/travisaction $CI_ACTION install
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - ./node_modules/.bin/travisaction $CI_ACTION before_script
script: ./node_modules/.bin/travisaction $CI_ACTION script
after_script: ./node_modules/.bin/travisaction $CI_ACTION after_script
branches:
  only:
  - master
env:
  matrix:
  - CI_ACTION=linters
  - CI_ACTION=unit-tests-in-firefox
matrix:
  fast_finish: true
notifications:
  email: false
