language: node_js
node_js:
  - "0.10.36"
before_install:
  - npm install -g npm@'2.11.0'
  - travis_retry make node_modules
  - source ./tests/ci/venv.sh
install: ./node_modules/.bin/travisaction $CI_ACTION install
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - ./node_modules/.bin/travisaction $CI_ACTION before_script
script: ./node_modules/.bin/travisaction $CI_ACTION script
after_script: ./node_modules/.bin/travisaction $CI_ACTION after_script
branches:
  only:
    - master-test
env:
  matrix:
    - CI_ACTION=linters
    - CI_ACTION=unit-tests-in-firefox
    - CI_ACTION=marionette_js PART=1 NBPARTS=10
matrix:
  fast_finish: true
notifications:
  email: false
