language: node_js
sudo: required
node_js:
  - "0.10.36"
before_install:
  - npm install -g travis-project-jobs
  - npm install -g npm@'2.11.0'
  - source ./tests/ci/venv.sh
install:
  - travisaction $CI_ACTION install
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - travisaction $CI_ACTION before_script
script: travisaction $CI_ACTION script
after_script: travisaction $CI_ACTION after_script
branches:
  only:
    - master-test
env:
  matrix:
    - CI_ACTION=linters
    - CI_ACTION=unit-tests-in-firefox APP=system
    - CI_ACTION=marionette_js PART=1 NBPARTS=20
matrix:
  fast_finish: true
notifications:
  email: false
