#! /bin/bash -vex

if [ -z "$TEST_APP" ]; then
  make test-integration TEST_MANIFEST=./shared/test/integration/travis-manifest.json
else
  make test-integration TEST_MANIFEST=./shared/test/integration/travis-manifest.json APP=$TEST_APP
fi

